# Generated by Django 3.2 on 2022-01-21 20:38

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('date_of_travel', models.DateField()),
                ('date_of_return', models.DateField(blank=True, null=True)),
                ('country_of_origin', django_countries.fields.CountryField(max_length=2)),
                ('country_of_destination', django_countries.fields.CountryField(max_length=2)),
                ('age_of_traveller', models.PositiveIntegerField()),
                ('is_supervised', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Travel Permit',
                'verbose_name_plural': 'Travel Permit',
                'ordering': ('-created_at',),
                'get_latest_by': ('-created_at',),
            },
        ),
    ]
