# Generated by Django 3.2 on 2022-01-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0002_auto_20220122_1050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
