# Generated by Django 3.2 on 2022-01-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0004_alter_permit_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
