# Generated by Django 3.2 on 2022-01-23 20:08

from django.db import migrations, models

import travel.validators


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0005_alter_permit_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permit",
            name="date_of_travel",
            field=models.DateField(
                validators=[
                    travel.validators.travel_date_less_present_date,
                    travel.validators.validate_weekday,
                    travel.validators.validate_minimum_date_of_travel,
                    travel.validators.validate_maximum_date_of_travel,
                ]
            ),
        ),
    ]
