# Generated by Django 3.2 on 2022-01-23 20:10

from django.db import migrations, models

import travel.validators


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0006_alter_permit_date_of_travel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permit",
            name="date_of_return",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[travel.validators.travel_date_less_present_date],
            ),
        ),
        migrations.AlterField(
            model_name="permit",
            name="date_of_travel",
            field=models.DateField(
                validators=[
                    travel.validators.validate_weekday,
                    travel.validators.validate_minimum_date_of_travel,
                    travel.validators.validate_maximum_date_of_travel,
                ]
            ),
        ),
    ]
